stages:
  - build
  - deploy-db
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-$CI_PIPELINE_ID
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  REGISTRY: gitlab-registry-$CI_PROJECT_NAME
  AGENT: objective-earth/objective-earth-wiki
  CONTEXT_DEV: $AGENT:test-agent
  HOST_DEV: oetestgitlab.smarter.codes

  # Change this to gitlab variables
  MEDIAWIKI_DB_HOST: entrypoint-mysql
  MEDIAWIKI_DB_TYPE: mysql
  MEDIAWIKI_DB_NAME: my_wiki
  MEDIAWIKI_DB_USER: root
  MEDIAWIKI_DB_PASSWORD: sakila
  # Change this to gitlab variables MR CI/CD
  HOST_MR: $CI_MERGE_REQUEST_ID.oe-test.smarter.codes
  MEDIAWIKI_DB_HOST_MR: mysql-$CI_MERGE_REQUEST_ID
  WG_SERVER_MR: https://$HOST_MR
  MEDIAWIKI_DB_TYPE_MR: mysql
  MEDIAWIKI_DB_NAME_MR: my_wiki
  MEDIAWIKI_DB_USER_MR: root
  MEDIAWIKI_DB_PASSWORD_MR: sakila

build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG_LATEST || echo "image for cache not found"
    - docker build --cache-from=$IMAGE_TAG_LATEST -t $IMAGE_TAG_LATEST -t $IMAGE_TAG .
    - docker push $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG
  only:
    - test
    - merge_requests

deploy-dev-mysql:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy-db
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CONTEXT_DEV
    - >-
      kubectl create namespace $CI_COMMIT_BRANCH
      -o yaml --dry-run=client | kubectl apply -f -
    - >-
      head /dev/urandom | tr -dc A-Za-z0-9 | head -c 10 |
      kubectl create --namespace=$CI_COMMIT_BRANCH
      secret generic mysqlauth
      --from-literal=rootUser=root
      --from-literal=rootHost=%
      --from-literal=rootPassword=/dev/stdin || :
    - kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-crds.yaml
    - kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-operator.yaml
    - >-
      sed -i
      -e 's|$MEDIAWIKI_DB_HOST|'"$MEDIAWIKI_DB_HOST"'|'
      kube-deployment-mysql.yml
    - kubectl apply --namespace=$CI_COMMIT_BRANCH -f kube-deployment-mysql.yml
  only:
    - test

deploy-dev-mediawiki:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  environment:
    name: deploy/$CI_COMMIT_BRANCH-$CI_PROJECT_NAME
    url: https://$HOST_DEV
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CONTEXT_DEV
    - >-
      kubectl create namespace $CI_COMMIT_BRANCH
      -o yaml --dry-run=client | kubectl apply -f -
    - >-
      kubectl create secret
      docker-registry $REGISTRY
      --namespace $CI_COMMIT_BRANCH
      --docker-server="$CI_REGISTRY"
      --docker-username="$CI_DEPLOY_USER"
      --docker-password="$CI_DEPLOY_PASSWORD"
      --docker-email="$GITLAB_USER_EMAIL"
      -o yaml --dry-run=client | kubectl apply -f -
    - >-
      sed -i 
      -e 's|$IMAGE_TAG|'"$IMAGE_TAG"'|'
      -e 's|$APP|'"$CI_PROJECT_NAME"'|'
      -e 's|$REGISTRY|'"$REGISTRY"'|'
      -e 's|$URL|'"$HOST_DEV"'|'
      -e 's|$WG_SERVER|'"https://$HOST_DEV"'|'
      -e 's|$MEDIAWIKI_DB_HOST|'"$MEDIAWIKI_DB_HOST"'|'
      -e 's|$MEDIAWIKI_DB_TYPE|'"$MEDIAWIKI_DB_TYPE"'|'
      -e 's|$MEDIAWIKI_DB_NAME|'"$MEDIAWIKI_DB_NAME"'|'
      -e 's|$MEDIAWIKI_DB_USER|'"$MEDIAWIKI_DB_USER"'|'
      -e 's|$PORT|'"80"'|'
      kube-deployment-mediawiki.yml
    - kubectl apply --namespace=$CI_COMMIT_BRANCH -f kube-deployment-mediawiki.yml
  only:
    - test

deploy-mr:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  environment:
    name: testing/$CI_PROJECT_NAME-$CI_MERGE_REQUEST_ID
    url: https://$CI_MERGE_REQUEST_ID.oe-test.smarter.codes
    on_stop: teardown-mr
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CONTEXT_DEV
    - >-
      kubectl create namespace $CI_MERGE_REQUEST_ID
      -o yaml --dry-run=client | kubectl apply -f -
    - >-
      kubectl create secret
      docker-registry $REGISTRY
      --namespace $CI_MERGE_REQUEST_ID
      --docker-server="$CI_REGISTRY"
      --docker-username="$CI_DEPLOY_USER"
      --docker-password="$CI_DEPLOY_PASSWORD"
      --docker-email="$GITLAB_USER_EMAIL"
      -o yaml --dry-run=client | kubectl apply -f -
    - >-
      sed -i 
      -e 's|$CI_MERGE_REQUEST_ID|'"$CI_MERGE_REQUEST_ID"'|'
      kube-deployment-mysql-mr.yml
    - kubectl apply --namespace=$CI_MERGE_REQUEST_ID -f kube-deployment-mysql-mr.yml
    - >-
      sed -i
      -e 's|$IMAGE_TAG|'"$IMAGE_TAG"'|'
      -e 's|$APP|'"$CI_PROJECT_NAME"'|'
      -e 's|$REGISTRY|'"$REGISTRY"'|'
      -e 's|$URL|'"$HOST_MR"'|'
      -e 's|$WG_SERVER|'"$WG_SERVER_MR"'|'
      -e 's|$MEDIAWIKI_DB_HOST|'"$MEDIAWIKI_DB_HOST_MR"'|'
      -e 's|$MEDIAWIKI_DB_TYPE|'"$MEDIAWIKI_DB_TYPE_MR"'|'
      -e 's|$MEDIAWIKI_DB_NAME|'"$MEDIAWIKI_DB_NAME_MR"'|'
      -e 's|$MEDIAWIKI_DB_USER|'"$MEDIAWIKI_DB_USER_MR"'|'
      -e 's|$MEDIAWIKI_DB_PASSWORD|'"$MEDIAWIKI_DB_PASSWORD_MR"'|'
      -e 's|$PORT|'"80"'|'
      kube-deployment-mediawiki.yml
    - kubectl apply --namespace=$CI_MERGE_REQUEST_ID -f kube-deployment-mediawiki.yml
  only:
    - merge_requests

teardown-mr:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  environment:
    name: testing/$CI_PROJECT_NAME-$CI_MERGE_REQUEST_ID
    action: stop
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CONTEXT_DEV
    - kubectl delete namespace $CI_MERGE_REQUEST_ID
  when: manual
  only:
    - merge_requests
