stages:
  - build
  - deploy-db
  - deploy

  
variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA-$CI_PIPELINE_ID
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest
  REGISTRY: gitlab-registry-$CI_PROJECT_NAME
  AGENT: objective-earth/objective-earth-wiki
  CONTEXT_DEV: $AGENT:test-agent  
  HOST: oetestgitlab.smarter.codes


build:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $IMAGE_TAG_LATEST || echo "image for cache not found"
    - docker build --cache-from=$IMAGE_TAG_LATEST -t $IMAGE_TAG_LATEST -t $IMAGE_TAG .
    - docker push $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG
  only:
    - test


deploy-mysql-test:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy-db
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CONTEXT_DEV
    - >-
      kubectl create namespace $CI_COMMIT_BRANCH
      -o yaml --dry-run=client | kubectl apply -f -
    - kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-crds.yaml
    - kubectl apply -f https://raw.githubusercontent.com/mysql/mysql-operator/trunk/deploy/deploy-operator.yaml
    - kubectl apply --namespace=$CI_COMMIT_BRANCH -f deploy-mysql.yml
  only:
    - test


deploy-mediawiki-test:
  image:
    name: bitnami/kubectl
    entrypoint: [""]
  stage: deploy
  environment:
    name: dev/$CI_COMMIT_BRANCH-$CI_PROJECT_NAME
    url: https://$HOST
  script:
    - kubectl config get-contexts
    - kubectl config use-context $CONTEXT_DEV
    - >-
      kubectl create namespace $CI_COMMIT_BRANCH
      -o yaml --dry-run=client | kubectl apply -f -
    - >-
      kubectl create secret
      docker-registry $REGISTRY
      --namespace $CI_COMMIT_BRANCH
      --docker-server="$CI_REGISTRY"
      --docker-username="$CI_DEPLOY_USER"
      --docker-password="$CI_DEPLOY_PASSWORD"
      --docker-email="$GITLAB_USER_EMAIL"
      -o yaml --dry-run=client | kubectl apply -f -
    - >-
      sed -i 
      -e 's|$IMAGE_TAG|'"$IMAGE_TAG"'|'
      -e 's|$APP|'"$CI_PROJECT_NAME"'|'
      -e 's|$REGISTRY|'"$REGISTRY"'|'
      -e 's|$URL|'"$HOST"'|'
      -e 's|$PORT|'"80"'|'
      deploy-mediawiki.yml
    - kubectl apply --namespace=$CI_COMMIT_BRANCH -f deploy-mediawiki.yml
  only:
    - test