apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysqltest
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 1
  router:
    instances: 1
  requests:
    storage: 2Gi