apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-$APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediawiki
  template:
    metadata:
      labels:
        app: mediawiki
    spec:
      containers:
        - name: mediawiki
          image: mediawiki:1.38
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint-mediawiki
spec:
  type: ClusterIP
  selector:
    app: mediawiki
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mediawiki
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - oe-test.smarter.codes
      secretName: oe-test.smarter.codes-tls
  rules:
    - host: oe-test.smarter.codes
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: entrypoint-mediawiki
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mayank.g@solutionbeyond.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx