apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-$APP
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $APP
  template:
    metadata:
      labels:
        app: $APP
    spec:
      containers:
        - name: container-$APP
          image: $IMAGE_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: $PORT
          env:
            - name: MEDIAWIKI_DB_TYPE
              value: "mysql"
            - name: MEDIAWIKI_DB_HOST
              value: "mysqltest"
            - name: MEDIAWIKI_DB_NAME
              value: "my_wiki"
            - name: MEDIAWIKI_DB_USER
              value: "root"
            - name: MEDIAWIKI_DB_PASSWORD
              value: "sakila"
      imagePullSecrets:
        - name: $REGISTRY
---
apiVersion: v1
kind: Service
metadata:
  name: entrypoint-$APP
spec:
  type: ClusterIP
  selector:
    app: $APP
  ports:
    - port: $PORT
      targetPort: $PORT
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-$APP
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - $URL
      secretName: $URL-tls
  rules:
    - host: $URL
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: entrypoint-$APP
                port:
                  number: $PORT
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mayank.g@solutionbeyond.net
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx