version: "3"

services:
  traefik:
    image: traefik:v1.7-alpine
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command: >
      --logLevel='INFO'
      --web
      --InsecureSkipVerify=true
      --defaultentrypoints=https,http
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS Redirect.EntryPoint:http'
      --retry
      --docker
      --docker.endpoint='unix:///var/run/docker.sock'
      --docker.exposedbydefault=true
      --docker.watch=true
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.protocol=http"
    networks:
      - docker_net

  objective-earth:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["/bin/bash", "/scripts/run.sh"]
    environment:
      MEDIAWIKI_DB_TYPE: mysql
      MEDIAWIKI_DB_HOST: mysqldb
      MEDIAWIKI_DB_NAME: oearth
      MEDIAWIKI_DB_USER: root
      MEDIAWIKI_DB_PASSWORD: changemeplease
      MEDIAWIKI_ADMIN_PASSWORD: changemeplease
      WG_SERVER: http://oe.localhost
    labels:
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:oe.localhost"
      - "traefik.protocol=http"
    networks:
      - docker_net

  mysqldb:
    image: mysql:8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: changemeplease
    networks:
      - docker_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: changemeplease
    labels:
      - "traefik.port=8000"
      - "traefik.frontend.rule=Host:php.localhost"
      - "traefik.protocol=http"
    networks:
      - docker_net

networks:
  docker_net:
    name: docker_net
    driver: bridge
