version: '3'
services:
  traefik:
    image: traefik:v1.7-alpine
    container_name: traefik
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    command: >
      --logLevel='INFO'
      --web
      --InsecureSkipVerify=true
      --defaultentrypoints=https,http
      --entryPoints='Name:http Address::80'
      --entryPoints='Name:https Address::443 TLS Redirect.EntryPoint:http'
      --retry
      --docker
      --docker.endpoint='unix:///var/run/docker.sock'
      --docker.exposedbydefault=true
      --docker.watch=true
    ports:
          - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.protocol=http"
    networks:
      - docker_net


  mediawiki:
    container_name: mediawiki
    restart: always
    ports:
      - 8080:80
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:mediawiki.localhost"
        - "traefik.protocol=http"
    networks:
      - docker_net
  
  database:

    image: mysql:8.0
    container_name: mysqldb
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: oearth
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_USER: wikimedia
      MYSQL_PASSWORD: changeme
    volumes:
      - /var/lib/mysql
      - ./init.sql:/data/application/init.sql

    networks:
      - docker_net


networks:
  docker_net:
    name: docker_net
    driver: bridge