apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: $MEDIAWIKI_DB_HOST
spec:
  secretName: mysqlauth
  tlsUseSelfSigned: true
  instances: $INSTANCES
  version: 8.0.30
  router:
    instances: 1
    version: 8.0.30
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  mycnf: |
    [mysqld]
    max_connections=162
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin/phpmyadmin
          ports:
            - containerPort: 8000            
          env:
            - name: PMA_HOST
              value: $MEDIAWIKI_DB_HOST
            - name: PMA_PORT
              value: "3306"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysqlauth
                  key: rootPassword
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
